-- Script para insertar productos del Festival EmprendeQuindío 2025
-- Ejecutar después de la migración create_emprende_quindio_marketplace

-- Insertar productos de ejemplo
INSERT INTO market_listings (
  titulo, descripcion, precio, categoria, institucion,
  vendedor_id, vendedor_nombre, imagen_url, rating, ventas, vistas,
  impacto_social, badge_emprendimiento, tipo_productor, equipo_info, activo
) VALUES
(
  'Pan de Leche con Relleno de Chocolate y Queso Costeño',
  'Postre innovador a base de cáscara y nuez de macadamia, creado por estudiantes del SENA en alianza con la IE Ramón Messa Londoño. Una fusión única que combina tradición colombiana con innovación quindiana. Producto destacado del Festival EmprendeQuindío 2025.',
  10000,
  'Innovadores',
  'IE Ramón Messa Londoño',
  'sena_team',
  'Equipo SENA',
  'https://www.mycolombianrecipes.com/wp-content/uploads/2015/07/Pan-de-Queso-Colombian-Style-Cheese-Bread-5.jpg',
  4.8,
  145,
  892,
  'Producto innovador creado por aprendices SENA, genera empleo juvenil',
  true,
  'SENA',
  '[
    {"nombre": "Jesús Alberto Nare Aponte", "documento": "PPT 4526136", "rol": "Coordinador SENA"},
    {"nombre": "Diego Alberto Ríos Flores", "documento": "T.I 1096671181", "rol": "Producción"},
    {"nombre": "Salomé Moncada Villa", "documento": "T.I 1183963061", "rol": "Marketing"},
    {"nombre": "Brayan Esteven Méndez Tobar", "documento": "T.I", "rol": "Logística"},
    {"nombre": "César Augusto Mosquera", "documento": "C.C. 1095178828 / T.I. 1095268742", "rol": "Calidad"}
  ]'::jsonb,
  true
),
(
  'Pan Tradicional Colombiano',
  'Pan fresco hecho por familias de estudiantes siguiendo recetas tradicionales quindianas. Horneado diariamente con ingredientes locales de alta calidad. Textura suave y sabor auténtico del campo cafetero.',
  2000,
  'Panadería',
  'IE Ramón Messa Londoño',
  'familia_001',
  'Familias RML',
  'https://www.mycolombianrecipes.com/wp-content/uploads/2020/06/12-Colombian-Breads-Collage.jpg',
  4.5,
  320,
  1240,
  'Apoya a familias productoras locales, tradición quindiana',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Donas Colombianas Artesanales',
  'Donas caseras elaboradas por graduados de la institución. Glaseadas y rellenas con cremas tradicionales. Recetas heredadas de generación en generación, con el toque especial del Quindío cafetero.',
  3000,
  'Panadería',
  'IE Ramón Messa Londoño',
  'familia_002',
  'Graduados RML',
  'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
  4.6,
  210,
  876,
  'Emprendimiento de egresados, genera ingresos para familias locales',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Galletas Cucas Colombianas',
  'Galletas crujientes de familias estudiantes con sabor tradicional del Quindío. Elaboradas con mantequilla de la región y azúcar morena. Perfectas para acompañar el café de la tarde.',
  4000,
  'Panadería',
  'IE Ramón Messa Londoño',
  'familia_003',
  'Familias RML',
  'https://sweetysalado.com/wp-content/uploads/2021/12/Galletas-Cucas-1.jpg',
  4.4,
  185,
  654,
  'Rescata recetas familiares tradicionales del Quindío',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Pandebono Tradicional',
  'Pandebono de queso costeño elaborado por estudiantes. Receta auténtica colombiana con harina de maíz y almidón de yuca. Horneado fresco diariamente, ideal para el desayuno quindiano.',
  2500,
  'Panadería',
  'IE Ramón Messa Londoño',
  'estudiante_001',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
  4.7,
  267,
  1032,
  'Producto elaborado por estudiantes, desarrollo de habilidades',
  true,
  'Escolar',
  '[]'::jsonb,
  true
),
(
  'Empanadas de Cambrai',
  'Empanadas tradicionales de cambrai rellenas de carne, preparadas por familias de la comunidad educativa. Masa crujiente con relleno jugoso y especiado al estilo quindiano.',
  1500,
  'Panadería',
  'IE Ramón Messa Londoño',
  'familia_004',
  'Familias RML',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
  4.5,
  412,
  1567,
  'Tradición familiar, ingresos para la comunidad escolar',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Tortas de Chocolate Caseras',
  'Tortas artesanales de chocolate elaboradas por familias. Postre tradicional con cacao colombiano de primera calidad. Perfectas para celebraciones y reuniones familiares del Quindío.',
  6000,
  'Postres',
  'IE Ramón Messa Londoño',
  'familia_005',
  'Familias RML',
  'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
  4.8,
  156,
  743,
  'Repostería familiar, promueve el consumo de cacao local',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Plátano Cultivado Orgánico',
  'Plátano fresco de cultivos escolares sostenibles. Cultivado sin pesticidas químicos por estudiantes en el proyecto agroecológico de la institución. Producto 100% quindiano.',
  3000,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'estudiante_002',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=800',
  4.6,
  298,
  956,
  'Agricultura sostenible estudiantil, educación ambiental',
  true,
  'Escolar',
  '[]'::jsonb,
  true
),
(
  'Lulo Fresco del Quindío',
  'Lulo cultivado por estudiantes en huertos escolares. Fruta tropical quindiana, perfecta para jugos y postres. Cosecha semanal, garantía de frescura y sabor autóctono.',
  2500,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'estudiante_003',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
  4.7,
  234,
  812,
  'Cultivo estudiantil sostenible, preserva frutas nativas',
  true,
  'Escolar',
  '[]'::jsonb,
  true
),
(
  'Lechuga Orgánica de Huerta',
  'Lechuga fresca de huertos escolares. Cultivada sin químicos por estudiantes del proyecto agroecológico. Cosecha diaria para garantizar máxima frescura y nutrientes.',
  1000,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'estudiante_004',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800',
  4.5,
  187,
  543,
  'Agricultura urbana escolar, alimentación saludable',
  true,
  'Escolar',
  '[]'::jsonb,
  true
),
(
  'Repollo Colombiano Fresco',
  'Repollo de cultivos familiares, saludable y fresco. Cultivado en parcelas comunitarias con técnicas tradicionales del campo quindiano. Rico en nutrientes.',
  1500,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'familia_006',
  'Familias RML',
  'https://images.unsplash.com/photo-1594282690343-7e3652e1f1e4?w=800',
  4.4,
  165,
  467,
  'Cultivo familiar comunitario, seguridad alimentaria',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Frijol Rojo Colombiano',
  'Frijol rojo cultivado tradicionalmente, base de platos típicos. Cosecha familiar con métodos ancestrales. Producto esencial de la dieta quindiana, alto en proteína.',
  2000,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'familia_007',
  'Familias RML',
  'https://images.unsplash.com/photo-1607418962355-d3bb9f040e32?w=800',
  4.6,
  243,
  721,
  'Preserva cultivos tradicionales, soberanía alimentaria',
  true,
  'Familiar',
  '[]'::jsonb,
  true
),
(
  'Tomate Chonto de Huerta',
  'Tomate fresco de cultivos escolares sostenibles. Variedad chonto ideal para salsas y ensaladas. Cultivado por estudiantes en invernaderos educativos.',
  1200,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'estudiante_005',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800',
  4.5,
  201,
  634,
  'Horticultura estudiantil, aprendizaje práctico',
  true,
  'Escolar',
  '[]'::jsonb,
  true
),
(
  'Piña Tropical del Quindío',
  'Piña dulce cultivada en el clima privilegiado del Quindío. Fruta fresca y jugosa, perfecta para consumo directo o jugos naturales. Cosecha sostenible estudiantil.',
  2500,
  'Cultivos',
  'IE Ramón Messa Londoño',
  'estudiante_006',
  'Estudiantes RML',
  'https://images.unsplash.com/photo-1587440871875-191322ee64b0?w=800',
  4.7,
  178,
  598,
  'Fruticultura tropical estudiantil, economía circular',
  true,
  'Escolar',
  '[]'::jsonb,
  true
)
ON CONFLICT DO NOTHING;
